---
deployment:
  tasks:
    - export DEPLOYPATH=/home/danielbe/public_html/fotografia/tutorial-registrarse-desde-celular/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp _config.yml $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .gitmodules $DEPLOYPATH
    - /bin/cp Gemfile $DEPLOYPATH
    - /bin/cp Gemfile.lock $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp -R node_modules/reveal.js $DEPLOYPATH
    - /bin/cp -R _includes $DEPLOYPATH
    - /bin/cp -R _layouts $DEPLOYPATH
    - /bin/cp -R _posts $DEPLOYPATH
    - /bin/cp -R script $DEPLOYPATH
